version: "3"

services:
  sa:
    image: linuxserver/letsencrypt
    ports:
      - 443:443
      - 80:80
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - URL=$DOMAIN
      - SUBDOMAINS=,
      - VALIDATION=http
    volumes:
      - ./volumes/letsencrypt/config:/config
