version: "3"

services:
  base:
    build: ./base
    volumes:
      - notebookdata:/data
    ports:
      - "8000:8000"

volumes:
  notebookdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/data/notebookdata'