version: "3"

services:
  jupyter:
    build: ./base
    volumes:
      - notebookdata:/data
    ports:
      - "8000:8000"

  nginx:
    image: arm64v8/nginx
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/letsencrypt/config/etc/letsencrypt/:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"

volumes:
  notebookdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/data/notebookdata'